orbs:
  react: 'thefrontside/react@0.2.0'
  aws-s3: circleci/aws-s3@1.0.16
version: 2
jobs:
  build:  
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - run: npm install
      - run: npm build
      - aws-s3/sync:
          from: dist
          to: 's3://elem.dashboard/'